### ISSUE TITLE
A possible idea for increamental reading/learning in org-fc

### ISSUE THREAD

**Issue by nowislewis** [l3kn/org-fc#130]
Hello everyone, I want to propose a idea for incremental reading in the wonderful org-fc. I have noticed a discussion here, https://github.com/l3kn/org-fc/issues/88 but I think there might be another approach:

1. As I understand, the purpose of incremental reading is to `continue reading` a book or article only after acquiring sufficient learning/memory. This leaves enough working memory available for futher learning in the brain, while the required prerequisite knowledge has already been retained in long-term memory—similar to RAM and hard disk storage.
2. Based on this idea, I have envisioned a plan:
   1. Suppose each book or article for study is treated as a `separate file`. We can create an org-fc card in this file, with the title being the book name, along with `article` and `suspend` tags.
   3. When we start review, first the program will start by checking all `cards with both article and suspend tags`.
   4. For each discovered card, inspect all other cards within `the same file or buffer`:
      1. Check the `review internal` status of these cards to see if the value is greater than 3 or another specified number. The purpose of this is to confirm that the prerequisite knowledge required to continue reading has already been `memorized and understood`.
      2. If the requirements are met, `remove` the suspend tag from the article tag
    5.  Then invoke the actual `org-fc-review-all` to start review
    6.  If we found a card with article, we can suspend this card, it has 2 advs:
         1. If we want to learn, we can `continue learning` this topic and make more cards
         2.  If we don't want to learn this topic by the time, we can continue `reviewing other cards`. 

There is no need to warry about we missed learning because everytime we start reviewing,  articles will be checked whether it satified the learning prerequisite knowledge

Due to my limited knowledge of elisp or org-fc, I'm unsure if this solution is easy to implement. Any possible assistance would be highly appreciated. :smile:

**Comment by l3kn** [comment]
What I've done for some math books is to replicate the outline in org mode, read though the book for short periods of time and then create cards for stuff I want to memorize in this structure. To keep track of finished and unfinished parts of the book I used the org-mode NEXT/TODO/DONE states.

Leaving aside the implementation details, my understanding of what you're proposing is to also treat these unread sections of the book/document as a kind of flashcard (or review item). 

A review session would then start with going over cards that are due (there is prerequisite knowledge we need to test)
and then continue with a new review item (the next article in the file that has not been read/processed yet?).

Maybe we can approach this with a new spacing algorithm not focused on memorizing facts,
e.g. it would ask you to read through the next chapter and you can spend some time on that,
then tell the algorithm that you're done, want to continue in the next review or want put it aside for some time.
This would be equivalent to NEXT/TODO/DONE states and scheduled dates in “vanilla” org-mode.

Does this match your idea of incremental reading?

**Comment by nowislewis** [comment]
You've proposed a great idea. The reason I tried using the method of detection intervals in org-fc was just a simple way to create a learning constraint. The approach you proposed is much more effective but may need a challenging algorithm.
Previously, I used Anki and then supermemo18 for similar review activities and met some problems:

I import the materials into SM18, then read a portion of the content to create `excerpt cards`. When SM18 pushes the excerpt cards to me, I convert them into `question-and-answer or close cards`, and `suspend` the cards. After some time, SM18 will push the cards I made back to me for memory. When I have memorized the content for a while, SM18 will push the article to me for `continued reading`. SM18 implements incremental reading through an algorithmic planning method, allowing me to freely read many books at the same time. But it is difficult for sm18 in such a common scenario, `blocking`.

For example, if you're struggling with section A.3 of article A, you may find that you often need to turn forward to A.2 and A.1 to see the definitions of some concepts, or need to read other books as prerequisite knowledge. This will block the brain's working memory space and make it `difficult to smoothly understand A.3`. Then you can stop reading for now and have 2 choices:
   1. Read other articles B and C while `waiting for the algorithm to prompt` you to revisit section A.3 (by then, you should be familiar with the knowledge from sections A.0 to A.2).
   2. Alternatively, you could `seek additional materials that support section A.3`, such as D and E, and even integrate their cards into the org file of article A. This way, you won’t be prompted to study section A `until you've mastered the supporting knowledge` from D and E, thus reducing the pressure of learning difficult articles.
  
Sm18 does very well in the 1st. But for 2nd choice, although sm18 provide a way to set `priorities for different cards`, it often push A.3 to you regardless of the learning quality of D and E, because it is difficult for the algorithm to automatically evaluate A.3 through the learning quality of D and E. It priority is just `global`.

As the amount of study materials increases, we might end up reading portions of dozens of articles each day. Have a long TODO reading list that records my progress on each article make it hard to choose what to learn. In this case, I can only select some articles to read, and I am not sure whether they are the most suitable materials to read at the moment.  

Even though algorithms like SM2, SM18, or FSRS may have differences in planning memory efficacy, they are not critical to learning. I believe that superficially memorizing concepts is not the best way to learn, we need first understand knowledge and then to memory.

**Comment by l3kn** [comment]
Very interesting!

I think tree structures are limiting but implementing ordering and dependency resolution in a knowledge graph hard,
so a tree (or even a linear) structure is a good place to start.

What we'll need is a way to tell apart (fully processed/refined) question-and-answer cards from pieces of the input document that require further processing/refinement.

This processing of the input document can take multiple forms, as you already described.
E.g. the initial  "input item" could be just an entry for the book which is refined into a list of chapters,
then the initial item is done (suspended) and each chapter becomes a new input item to be processed
(into sub-chapters, excerpt cards, summaries and at some point question-and-answer cards).

> [...] seek additional materials that support section A.3 [...]

Encountering A.3 (even if it is already a question-answer card that's hard to remember) reverses this process.
Now during review, we can decide that this card needs further refinement, and solve this by adding support material D and E.
In a tree structure this would mean inserting it somewhere before A.3.

In org-fc the review process is guided by two algorithms, a spacing algorithm determining when a card is due for review
and reacting to user ratings, and a scheduler using this spacing information to create a review session.

What you can already do in org-fc is to use the `noop` spacing algorithm (the card is always due, until you suspend it)
together with the `ordered` scheduler, then end the review after you have refined the first new input item.

This feels very linear but I'm not sure how a more “tree like” approach could look like.
Any suggestions how we could improve on this?

A personal example: 
Reading “Contemporary Abstract Algebra”, I've processed chapters 1-6 down to question-answer cards 
and the next chapters are
- 7. Cosets and Lagrange's Theorem
- 8. External Direct Products

Towards the end of chapter 7 there are some theorems I need to look deeper into (high mental effort)
while chapter 8 starts with some easy definitions (low mental effort, not blocked by these theorems).
In this case, I broke the linear structure by creating cards for the definitions.
I don't know how this would fit into the review process which is purely linear (go through this list of cards)
in the current version of org-fc.

**Comment by nowislewis** [comment]
A purely linear review is not an effective method for memory retention. Studying A for three days, then B for three days, and finally C for three days is not ideal. The effectiveness of spaced repetition lies in `extending the intervals between reviews without significantly increasing study time`, which facilitates long-term memory and knowledge absorption. Instead of the above method, it might be better to study A, B, and C each for one day at a time, and then repeat, as the review pattern for A  would be A, nop, nop, A, nop, nop, A, nop, nop. This benefit only a little from the spaced repetition algorithm but is still better than continuous three-day study sessions.

Regarding your example, I prefer the following approach with the idea in the first comment. To clarify the usage, I'll provide a specific example, although the core idea is very simple
There are two choices:

1. First, if all chapters are in `a single org file`:

- Chapter 6
  - card1
  - ...
- Chapter 7
  - card1
  - card2
  - 
Currently, Chapter 7 needs additional time before review, so we set the current study progress title to `article & suspend`, and continue with Chapter 8 and even Chapter 9, covering all understandable content cards.
- Chapter 6
  - card1
  - ...
- Chapter 7
  - card1
  -  card2,
- Chapter 8
  - card1
  - ..
 - Chapter 9
  - card1
  - ..
-  Continue reading: :article:suspend:
Chapter 7,
Chapter 9

We can set the review order to `random`, which will push all prepared cards to us randomly. Once org-fc detects that all cards in the file have been reviewed to some extent, it will insert study process card into review and prompt us to continue reading Chapter 7 or subsequent chapters. This approach ensures that by the time you move on to later chapters, you have understood other ones.

2. I lean towards another method, using `a new org file` whenever we hit a learning block:
For example, in `article.org`:
- Chapter 6
  - card1
  - ...
- Chapter 7
  - card1
  - card2
- Continue reading: :article:suspend:
Chapter 7

At this point, we stop reading chapter 7 and begin to collect materials D and E,  to make cards to aid the continuation of Chapter 7:
`D.org`
`E.org`
Meanwhile, we can also study Chapter 8:
`article-chap8.org`

We can link D.org and E.org within article.org:
In `article.org:`
- Chapter 6
  - card1
  - ...
- Chapter 7
  - card1
  - card2
- Continue reading: :article:suspend:
Chapter 7
[[file:D.org]]
[[file:E.org]]

If Chapter 8 helps in reviewing Chapter 7, we can include it too.

When we start a review, org-fc will detect all cards with the article & suspend tag. Upon encountering the continue card of Chapter 7, it will check the contents of D and E. If all cards in D and E have been sufficiently reviewed, it will remove the suspend status of Chapter 7, `schedule all review cards, and prompt us to start the review`.

If Chapter 8 is not highly dependent on Chapter 7, it will naturally be reviewed. If we want to prioritize the study of Chapter 7 after Chapter 8, `linking` Chapter 8 into Chapter 7 will work.

The core idea is to decide on studying a material based on the assessed memory retention of a batch of cards. While the current method uses `files`, it could also be determined by the cards `in a directory` or under `a large title`. I prefer files for greater flexibility. You can organize a folder for "Contemporary Abstract Algebra":
`ls` Contemporary Abstract Algebra:
- Chapters 1–7.org
- Chapter 8.org
- Chapters 9-10.org

Each file split signifies that when we reached that point, we included other materials such as D, E, or Chapter 8 as prerequisites during the review investment for Chapter 7. This method requires ensuring that no card is included in the same review process twice to avoid forming cyclic graphs.

You can also use plugins like Denote or Org-roam to make cards or links. In any case, our revision has turned into a form of random learning `within a directed acyclic graph`.

Certainly, the solution I proposed in the first comment still has many imperfections, such as deciding how many internals are appropriate for comparison. Moreover, I am not sure about the cost of implementing this step in org-fc.

**Comment by nowislewis** [comment]
> In org-fc the review process is guided by two algorithms, a spacing algorithm determining when a card is due for review and reacting to user ratings, and a scheduler using this spacing information to create a review session.
> 
> What you can already do in org-fc is to use the `noop` spacing algorithm (the card is always due, until you suspend it) together with the `ordered` scheduler, then end the review after you have refined the first new input item.

I tried this "linear" method and I think this method has already had some effect, the downside is that I can only review one file at a time, so I need to manually look for multiple files to review. But I think a linear review would be a relatively easy way to implement and work, its most effective feature is that it implements "block" without requiring the user to manually search for cards

**Comment by nowislewis** [comment]
For the processing of excerpts, I currently use a very simple approach and it works very well. The general idea is: 

1. import excerpts: every time I read a book, I will produce a lot of excerpts (org-noter, zotero, etc.), I put the excerpts from this reading into the corresponding org file, and then run a simple function I wrote, automatically process all the excerpts into org-fc normal card with a special tag, and then org-fc-resume. The process is very simple and requires no operation.

2.Processing: When I encounter this type of card in Reivew, I consider deleting or rewriting it to a suitable org-fc card

Such advantages are:

1. There is no need for an additional dedicated card production phase，I just need org-fc-review-all, everything works

2. A lot of the knowledge we excerpted when we read it, and when we look at it the next day, we find that it is not necessary, and we need to delete or rewrite it

3. It reduces the burden when reading, you only need to read when reading, you don't need to think about card making, and it is easier to focus

**Comment by nowislewis** [comment]
The org-fc code is very well written, and I wrote a simple function to determine if an article can be read or not. If anyone wants to try:

```elisp
(defun org-fc-clarify-continue-reading ()
  "By determining whether all the cards in the file containing the article have been reviewed, decide whether this article can continue to be read."
  (interactive)
  (dolist (card (org-fc-index '(:filter (and (tag "suspended") (and (tag "article"))))))
    (let ((file_path (oref (oref card file) path))
          (should-review t))
      (dolist (file-card (org-fc-index `(:paths ,file_path :filter (not (tag "suspended")))))
        (if (> (plist-get (oref (car (oref file-card positions)) data) :interval)  0.0)
            (setq should-review nil)))
      (if should-review
          (save-window-excursion
            (save-excursion
              (message "unsuspending card: %s" (oref card title))
              (org-id-goto (oref card id))
              (let ((current-tags (org-get-tags)))
                (org-set-tags '())
                (org-set-tags '("fc" "article"))
                (save-buffer)
                )
              )))
      )))

```

**Comment by nowislewis** [comment]
The org-fc code is very well written, and I wrote a simple function to determine if an article can be read or not. If anyone wants to try:
```elisp
(defun org-fc-clarify-continue-reading ()
  "By determining whether all the cards in the file containing the article have been reviewed, decide whether this article can continue to be read."
  (interactive)
  (dolist (card (org-fc-index '(:filter (and (tag "suspended") (and (tag "article"))))))
    (let ((file_path (oref (oref card file) path))
          (should-review t))
      (dolist (file-card (org-fc-index `(:paths ,file_path :filter (not (tag "suspended")))))
        (if (< (plist-get (oref (car (oref file-card positions)) data) :interval)  1)
            (setq should-review nil)))
      (if should-review
          (save-window-excursion
            (save-excursion
              (message "unsuspending card: %s" (oref card title))
              (org-id-goto (oref card id))
              (let ((current-tags (org-get-tags)))
                (org-set-tags '())
                (org-set-tags '("fc" "article"))
                (save-buffer)
                )
              )))
      ))
  )
```
