### ISSUE TITLE
Cannot start org-fc-dashboard, xargs: unmatched single quote

### ISSUE THREAD

**Issue by mroman42** [l3kn/org-fc#19]
I am getting `(wrong-type-argument stringp nil)` when calling `org-fc-dashboard`. Debugging I get to this error in `org-fc-awk--key-value-parse`.

``` emacs lisp
  string-to-number(nil)
  (list (intern (concat ":" (car kv))) (string-to-number (car (cdr kv))))
  (let ((kv (split-string kv "\11"))) (list (intern (concat ":" (car kv))) (string-to-number (car (cdr kv)))))
  (closure ((input . "xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option\ntotal\0110\nsuspended\0110\ncreated-day\0110\ncreated-week\0110\ncreated-month\0110\n") t) (kv) (let ((kv (split-string kv "\11"))) (list (intern (concat ":" (car kv))) (string-to-number (car (cdr kv))))))("xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option")
```

Any idea on what I am doing wrong? I am using Emacs 27.0.5, Org Mode 9.4 (Doom Emacs).  My configuration is copied from the readme. I am using straight.el, but after reading #16 I tried copying the files from `/repos` to `/build`.

**Comment by l3kn** [comment]
Can you run the following code and let me know what the result is?
I'm not sure where the unmatched single quote could be coming from.

``` emacs-lisp
(pp 
 (org-fc-awk--pipe
  (org-fc-awk--find org-fc-directories)
  (org-fc-awk--xargs
   (org-fc-awk--command
    "awk/index_cards.awk"
    :utils t
    :variables (org-fc-awk--indexer-variables))))
```

**Comment by mroman42** [comment]
Solved. The problem was on my side, I had a file _with a single quote on the name_. Trying to run the output of your code gave me the clue. I am closing the issue; if someone encounters this problem, it is likely due to quotes on a filename.

In case it is still useful:
```
"find ~/deft/ -name \"[a-Z0-9_]*.org\" | xargs -n 2500 -P 4 gawk -v fc_tag=fc -v suspended_tag=suspended -v type_property=FC_TYPE -v created_property=FC_CREATED -v review_data_drawer=REVIEW_DATA -f /home/mario/.emacs.d/.local/straight/build/org-fc/awk/utils.awk -f /home/mario/.emacs.d/.local/straight/build/org-fc/awk/index_cards.awk "
```

Thank you, both for the quick response and for developing org-fc.

**Comment by l3kn** [comment]
I think having to rename files to make org-fc work correctly is still an issue.
I've pushed a change to the find / xargs commands that makes them work with filenames containing quotes.
