### ISSUE TITLE
`org-fc-demo` produces "No cards due right now"

### ISSUE THREAD

**Issue by dimitry12** [l3kn/org-fc#21]
`M-x org-fc-demo` opens the demo file, but nothing is due for review.

Upon inspection I can see that in `REVIEW_DATA` drawer due date is `2000-01-01T00:00:00Z` - in the past, and I assume that makes the card due for review.

Might be unrelated, but with `M-x org-fc-type-double-init` on a heading+text-entry I get `Wrong type argument: hash-table-p, nil` error. The `PROPERTIES` drawer is populated,  but `REVIEW_DATA` is not. Also the card does not get `:fc:`-tag. On such newly setup card `org-fc-review-buffer` also says "No cards due right now"

**Comment by l3kn** [comment]
Is there an `ID:` property in the `PROPERTIES` drawer?

There should be no code working with hash tables in org-fc, maybe it's an issue with org.
Which org version are you using? (`M-x org-version`)

You might be able to get more information on where the error is occuring with `M-x toggle-debug-on-error`, then runnig `M-x org-fc-type-double-init` again.

**Comment by dimitry12** [comment]
> Is there an `ID:` property in the `PROPERTIES` drawer?

Yes, `M-x org-fc-type-double-init` creates an `ID` property

> There should be no code working with hash tables in org-fc, maybe it's an issue with org.
> Which org version are you using? (`M-x org-version`)

`Org mode version 9.4`. I am on vanilla Doom Emacs.

> 
> You might be able to get more information on where the error is occuring with `M-x toggle-debug-on-error`, then running `M-x org-fc-type-double-init` again.

```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  puthash("43886d3f-63b6-4d13-9fe3-dc7d21a1a6ae" "~/Dropbox/private/KB/test_fc_card.org" nil)
  org-id-add-location("43886d3f-63b6-4d13-9fe3-dc7d21a1a6ae" "/Users/dzmitry/Dropbox/private/KB/test_fc_card.org")
  org-id-get(23 create)
  org-id-get-create()
  org-fc--init-card("double")
  org-fc-type-double-init()
  funcall-interactively(org-fc-type-double-init)
  call-interactively(org-fc-type-double-init record nil)
  command-execute(org-fc-type-double-init record)
  counsel-M-x-action("org-fc-type-double-init")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "org-fc-type-double-init" "org-version" "org-fc-review-buffer" "org-fc-review-all" "org-fc-dashboard" "org-fc-update" "org-fc-type-normal-flip" "org-fc-demo" "org-fc-type-normal-init" "org-fc-review" "org-fc-type-normal-setup" "org-roam-today" "org-fc-tag-card" "org-fc-review-quit" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "lsp!" "mail" "mpuz" "ping" "pong" ...) :predicate #f(compiled-function (x) #<bytecode 0x44e78e71>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

Workaround I found:
- do `M-x org-id-get-create` on a card first (`ID` property appears)
- then `M-x  org-fc-type-double-init` executes without failure: `:fc:`-tag is added to the headline, additional properties appear, `REVIEW_DATA`-table appears

A bit later I found that adding the  following to `~/.doom.d/config.el` fixed the `org-fc-type-double-init`-problem:
```
(setq org-id-locations-file "/Users/dzmitry/Dropbox/private/KB/.org-id-locations"
        org-id-track-globally t)
```

**Comment by dimitry12** [comment]
Ok, now that I can init cards, I still can not review. Newly initialized cards looks like:
```
#+TITLE: Test FC Card
* Test FC Card :fc:
:PROPERTIES:
:ID:       b755f4a4-c523-480f-b712-dc5ebced703f
:FC_CREATED: 2020-04-19T22:34:44Z
:FC_TYPE:  double
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    |  2.5 |   0 |        0 | 2020-04-19T22:34:44Z |
| back     |  2.5 |   0 |        0 | 2020-04-19T22:34:44Z |
:END:
This is the card's  body
```
and `M-x  org-fc-review-buffer` says `No cards due right now`. Just like `org-fc-demo`

**Comment by dimitry12** [comment]
I am on MacOS with macports:
```
bash-5.0$ which gawk
/opt/local/bin/gawk
bash-5.0$ gawk --version
GNU Awk 5.1.0, API: 3.0
```

same gawk version if checking with `M-x shell-command`

**Comment by dimitry12** [comment]
awk-scripts seems to be working:

```
bash-5.0$ cat ~/Dropbox/private/KB/test_fc_card.org
#+TITLE: Test FC Card
* Test FC Card :fc:
:PROPERTIES:
:FC_CREATED: 2020-04-19T22:54:20Z
:FC_TYPE:  double
:ID:       e8acb3c8-5413-453a-a6db-0823b42f491b
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    |  2.5 |   0 |        0 | 2020-04-19T22:54:20Z |
| back     |  2.5 |   0 |        0 | 2020-04-19T22:54:20Z |
:END:

This is the card's  body
```
```
bash-5.0$ gawk -f utils.awk -f  index_positions.awk ~/Dropbox/private/KB/test_fc_card.org | gawk -f utils.awk -f filter_due.awk
/Users/dzmitry/Dropbox/private/KB/test_fc_card.org      e8acb3c8-5413-453a-a6db-0823b42f491b    double  0       front   2.5     0       0       2020-04-19T22:54:20Z
/Users/dzmitry/Dropbox/private/KB/test_fc_card.org      e8acb3c8-5413-453a-a6db-0823b42f491b    double  0       back    2.5     0       0       2020-04-19T22:54:20Z
```
```
bash-5.0$ pwd
/Users/dzmitry/.emacs.d/.local/straight/repos/org-fc/awk
```

**Comment by l3kn** [comment]
I think the ID tracking issue is not related to org-fc,
in my config I'm using `(setq org-id-track-globally nil)` to disable it
because it gets very slow when there are a lot of files with IDs.

Your settings should be fine, too.

Are `find` and `xargs` insalled on your machine?

You can check that with

``` emacs-lisp
(shell-command-to-string
 (org-fc-awk--pipe
  (org-fc-awk--find (list "~/Dropbox/private/KB/test_fc_card.org"))
  (org-fc-awk--xargs "echo")))
```

**Comment by dimitry12** [comment]
I've installed `findutils` for macports, which makes `find` and `xargs` available (`M-x shell-command` with `xargs --version && find --version && gawk --version`):
```
xargs (GNU findutils) 4.7.0
....
find (GNU findutils) 4.7.0
....
GNU Awk 5.1.0, API: 3.0
```

With
```
(shell-command-to-string
 (org-fc-awk--pipe
  (org-fc-awk--find (list "~/Dropbox/private/KB/test_fc_card.org"))
  (org-fc-awk--xargs "echo")))
```
I get:
```
''
''
```

I found (epirically) that from macports, `find` does not support regex in basename (`-name`).  Changing `org-fc-awk--find-name` to `"*.org"` (was `"[a-Z0-9_]*.org"`) fixed the problem for me.

**Comment by l3kn** [comment]
One problem with using `-name "*.org"` is that it includes temporary / backup files that start with a ".".

I've found a better way to exclude those using `find dir/ -name "*.org" -not -name ".*"`,
can you check if that works with your version of `find`?

If so, I'll push that change to make sure `org-fc` works on MacOS without any manual changes.

Are `sudo port install gawk` and `sudo port install findutils` the correct commands for installing `gawk`, `find` and `xargs`?
I'd like to add them to the README to document how to set up org-fc on MacOS.

**Comment by dimitry12** [comment]
@l3kn 

`find dir/ -name "*.org" -not -name ".*"` works, thank you for suggesting this!

For macports:
- `sudo port install gawk findutils` installs `gawk` and newer versions of `xargs`, `find`
- I had to `export PATH="/opt/local/libexec/gnubin:/opt/local/bin:$PATH"` (and then `~/.emacs.d/bin/doom sync` to "freeze" the updated path in `~/.emacs.d/.local/env`)

**Comment by l3kn** [comment]
Thanks for your help, org-fc now uses `find` with `-not` and I've removed the `org-fc-awk--find-name` variable.

Let me know if you run into any other problems.

**Comment by dimitry12** [comment]
I will be migrating from org-drill and will be happy to report and help with any problems I find.

@l3kn Thank you for the package!
