### ISSUE TITLE
Tag based review

### ISSUE THREAD

**Issue by visika** [l3kn/org-fc#22]
It would be nice if I could filter what subject to review based on tags.
Right now I see I can add tags but they aren't actually of any use, or do they?

Ideally when doing org-fc-review, after the context menu with options all and buffer, another menu would ask for which tags to include in the review.

**Comment by visika** [comment]
So I tinkered a bit with the editor and discovered that if I click on a tag, emacs will list all the entries with that tag.

From there I can execute `org-fc-review` and choose the context _buffer_. This way I'll review only the entries with the chosen tag.

Is this the preferred way to achieve the result?

**Comment by l3kn** [comment]
I didn't know about the tag search feature, but it seems like it only searches for the tag in org agenda files. Because of the large number of flashcard files I'm using, relying on org-agenda features is not an option.

I'll try to add support for tags to the awk indexer scripts, then we can implement filters on top of that
(e.g. for only reviewing cards of a certain type / with a certain tag).

I'd like to keep the review context menu as simple as possible, adding a way of defining custom review contexts (e.g. all cards in `paths` tagged with `foo`) might be preferrable to adding a second tag-selection step to `org-fc-review`.

Can you tell me more about how you are using tags with org-fc so I can take that into consideration when implementing these filters?

**Comment by visika** [comment]
I'm using org-fc to review my notes from lesson.
Having different courses, I prefer to focus on one subject at a time during the day.
Using tags makes this easy, but indeed I see that sometimes it takes time to find all of them with the org-agenda search.

It could be preferable, but not of primary importance, to be able to filter based on multiple tags, e.g. _theorem_ and _statistical mechanics_ tags.

**Comment by l3kn** [comment]
The biggest issue I've run into so far is handling tag inheritance with the awk scripts,
but I think I've found a good solution that supports almost all the org features
(besides including `#+FILETAGS` using `#+SETUPFILE`).

Do you have any preferences in terms of the query syntax?

One based on s-expressions like `(and (tag "theorem") (tag "statistical mechanics"))`
is pretty easy to implement and could be used to register a review-context for each course.

**Comment by visika** [comment]
No, I don't have any preference. I'm pretty novice in elisp.

**Comment by l3kn** [comment]
@visika, can you help me test this new feature to make sure it works as you'd expect it to?

To do so, check out the https://github.com/l3kn/org-fc/tree/review-filters branch,
you can find the documentation for the new filters / contexts at https://github.com/l3kn/org-fc/tree/review-filters#review-contexts.

If you need any help with this, let me know how you installed org-fc
(using straigt or from source?).

**Comment by visika** [comment]
Hi, I updated to master right now as I see the relevant commits are merged.
It looks very promising! But it's broken for me, I get the error message 
`org-fc-awk-index-paths: Wrong type argument: sequencep, gawk:`
when I try to execute org-fc commands like review or demo.

**Comment by l3kn** [comment]
That looks like gawk throws an error, I've yet to rewrite the awk wrapper functions to turn those into more meaningful error messages.

Can you run the following piece of code and let me know what the result is?

``` emacs-lisp
    (shell-command-to-string
     (org-fc-awk--pipe
      (org-fc-awk--find org-fc-directories)
      (org-fc-awk--xargs
       (org-fc-awk--command
        "awk/index.awk"
        :utils t
        :variables (org-fc-awk--indexer-variables)))))
```

**Comment by visika** [comment]
Initially I got an error on that. Here's the output:
```
"gawk: fatale: non riesco ad aprire file sorgente
`/home/user/.emacs.d/.local/straight/build/org-fc/awk/utils.awk'
in lettura (File o directory non esistente)
```
that translates to
```
"gawk: fatal: can't open source file
`/home/user/.emacs.d/.local/straight/build/org-fc/awk/utils.awk'
in read mode (File or directory non existent)
```

I tried to rebuild the package from scratch and now it works well, although there is still no org-fc/awk folder. The command outputs a list with data about my flashcards.

**Comment by visika** [comment]
Also, and most importantly, the context filtering works great!

**Comment by l3kn** [comment]
Seems like an issue related to #20 then, I'll see if there is some way of configuring staight so it symlinks the awk files, too, the `:files` option looks promising.

I'll close this issue for now, let me know if you run into any problems
or if you have an idea for other filters that could be useful.
