### ISSUE TITLE
[RFC] Replace review hydras with `read-key`

### ISSUE THREAD

**Issue by l3kn** [l3kn/org-fc#28]
During review, there are two times user input / keys is read, once to flip the card and once to rate it.
Currently that's implemented using two hydras.

Because there is no way to block and return a value from a hydra (e.g. the rating), `org-fc-review-next-card` opens the flip hydra, this hydra calls `org-fc-review-flip` which executes the cards flip-function and then opens the rating hydra. The rating hydra calls `org-fc-review-rate` which calls `org-fc-review-next-card` to review the next card.

So the "review loop" is actually a sequence of four functions calling each other.

My main problem with this is that it's not very elegant and parts of the review logic are spread out over multiple functions.

It also prevents me from implementing two features I have planned:
1. card types with different review types per position, e.g. a double card where one position requires text input (no flipping) while the other position is flipped normally
2. audio for cards that's played either when the card is presented or flipped.
A key for replaying the audio file is hard to implement because hydras are not designed to have their keymaps changed after they are defined.

I've tried using two minor-modes instead of the hydras, but that requires a bunch of hacks to make sure the keys work with evil-mode enabled.

Another problem is that EmacsLisp has no TCO, and while I haven't run into this yet, I'm pretty sure that reviewing enough cards in a row (estimate: ~600) could trigger an "Variable binding depth exceeds max-specpdl-size" error.

My proposed solution is to replace the hydras with `read-key` and a nicely formatted prompt,
which would allow rewriting `org-fc-review-next-card` to use a `while`-loop.

**Comment by doolio** [comment]
Would using [magit/transient](https://github.com/magit/transient) instead of a hydra solve the problem?

**Comment by l3kn** [comment]
As I understand it, magit/transient is better suited for complex / multi-step key bindings,
org-fc only needs to read a single key each time.

I've found a workaround for my issues with evil-mode by using `evil-define-minor-mode-key`
and I'm currently testing a variant of the review loop using two minor modes.

This doesn't solve the problems with the review logic being spread across multiple functions
and reviewing lots of cards might still exhaust the variable binding depth,
but it would allow users to easily redefine keys and extensions (e.g. for playing audio)
can add their keys to one of the modes.

**Comment by l3kn** [comment]
Closing, a new review process based on two minor modes has been merged.
