### ISSUE TITLE
Treat contents of a drawer as content of a heading

### ISSUE THREAD

**Issue by natask** [l3kn/org-fc#30]
I place notes within a NOTES drawer. I would like org-fc to treat contents of that drawer as content of a heading. What would be the best way to go about this.

**Comment by l3kn** [comment]
In the current implementation there's a function `org-fc-hide-drawers` that hides all drawers before showing a card for review, I think the best solution would be adding a customizable list of drawers that should (not) be hidden.

**Comment by natask** [comment]
I will look into it. what will be nice if cloze also worked with it.

**Comment by l3kn** [comment]
If I understand this correcty, you want to use cloze deletions inside your `:NOTES:` drawer?
When the drawer is not hidden before the review, that should just work.

``` emacs-lisp
(defcustom org-fc-hidden-drawers
  (list "PROPERTIES" org-fc-review-data-drawer)
  "List of drawers that are hidden during review.")

(defun org-fc-hide-drawers ()
  "Hide all drawers in `org-fc-hidden-drawers' after point."
  (save-excursion
    (while (re-search-forward org-drawer-regexp nil t)
      (let ((start (1- (match-beginning 0)))
            (name (match-string 1))
            (end))
        (if (re-search-forward ":END:" nil t)
            (setq end (point))
          (error "No :END: found for drawer"))
        (if (member name org-fc-hidden-drawers)
            (org-fc-hide-region start end))))))
```

You can try this definition of `org-fc-hide-drawers` and see if it works as you'd expect.

**Comment by natask** [comment]
very cool, works like a charm. I modified it so that it is a white list rather than a black list.
``` elisp
   (defcustom org-fc-shown-drawers
     (list "NOTES")
     "List of drawers that are shown during review.")
   (defun org-fc-hide-drawers ()
     "Hide all drawers except onces in `org-fc-shown-drawers' after point."
     (save-excursion
       (org-fc-hide-schedule)
       (org-fc-hide-deadline)
       (while (re-search-forward org-drawer-regexp nil t)
         (let ((start (1- (match-beginning 0)))
               (name (match-string 1))
               (end))
           (if (re-search-forward ":END:" nil t)
               (setq end (point))
             (error "No :END: found for drawer"))
           (if (member name org-fc-shown-drawers)
               (progn
                (org-flag-drawer nil nil start end)
                )
               (org-fc-hide-region start end)
            )))))

   (defun org-fc-hide-deadline ()
     "Hide all deadlines tags in after point."
     (save-excursion
       (while (re-search-forward org-deadline-line-regexp nil t)
         (let ((start (1- (match-beginning 0)))
               (end   (match-end 0)))
               (org-fc-hide-region start end)
            ))))
  (defun org-fc-hide-schedule ()
     "Hide all scheduled tags in after point."
     (save-excursion
       (while (re-search-forward (concat "\\<\\(" org-scheduled-string "\\).*") nil t)
         (let ((start (1- (match-beginning 0)))
               (end   (match-end 0)))
               (org-fc-hide-region start end)
            ))))

```
I added stuff to hide scheduled and deadline tags as well. 
Thanks for the hard work!

**Comment by l3kn** [comment]
I think both of these features (not hiding some drawers, hiding keywords)
should be included in org-fc, I'm just not sure if a whitelist or a blacklist of drawer names would be better. Why do you prefer the blacklist variant?

Btw, `org-keyword-time-regexp` which matches all kinds of timestamp-keywords.

> [...] placing them in org-fc-review-next-card is more appropriate but for now it works well.

That's a good point, there should be a hook that runs when cards are set up for review.

**Comment by natask** [comment]
I prefer the White list approach more for a couple of reasons.
- It is more likely the case that the drawers to be shown are consistent over headings and over time than drawers to be hidden. 
  - I say this because as an example, I may start using an external tool that adds drawers to my org-fc headlines. It is mostly likely the case that I don't want this drawer to appear in org-fc. Therefore if org-fc is implementing a Black list approach, I would need to modify the variable while I wouldn't if it was implement a white list approach.
  - Different org-fc headlines may have different drawers I want to hide. and this may change over time. This means that I would need to find a maximal union set of all the sets of drawers I want to hidden for each heading. A single set of drawers to be shown will cover all of them, unless I want different set of drawers to be shown for each heading in which case a more sophisticated approach (an associated list) is required. A bit contrived sure but it illustrates the point. 
- The number of drawers shown is most likely to be smaller than the drawers hidden.

They both will get the job done in theory, but I think in terms of maintainability and cleanness, a white list approach is more suited here.

**Comment by l3kn** [comment]
These changes are now included in org-fc,
with the small change that I renamed `org-fc-shown-drawers` to `org-fc-drawer-whitelist`.
