### ISSUE TITLE
Call for Stats

### ISSUE THREAD

**Issue by l3kn** [l3kn/org-fc#36]
Going through my review history (~140k reviews) I've discovered that the recall rate is significantly worse
if the last rating was "hard".

I'm currently testing a new version of the algorithm (which can be enabled with `(setq org-fc-algorithm 'sm-v2)`)
but after 17k reviews with it, I still don't have enough data points to tell if it is better than the previous version.

If anyone is interested in helping with this, please leave a comment on this issue.

I'd need the review history file and a list of all card / positions.
If enough users are interested in helping with this,
I'll write a script that packages this data in a single file,
removing / replacing the filenames as these could be considered sensitive information.

**Comment by natask** [comment]
my review history file is statistically insignificant. I will contribute when it is larger.
