### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by ram535** [l3kn/org-fc#37]
I am having this error after updating.

```
Error (use-package): org-fc/:config: Cannot open load file: No such file or directory, org-fc-hydra
```

```
(use-package hydra)

(use-package org-fc
  :straight (org-fc :type git :host github :repo "l3kn/org-fc" :files (:defaults "awk" "demo.org"))
  :custom
   (org-fc-directories '("~/org/roams"))
  :config
  (require 'org-fc-hydra))
```

**Comment by l3kn** [comment]
I've moved `org-fc-hydra.el` to the `contrib/` folder.
I was expecting that to be handled by `:defaults`,
can you try if `:files (:defaults "contrib" "awk" "demo.org")` works?

**Comment by wedens** [comment]
This recipe should work: `(:host github :repo "l3kn/org-fc"  :files (:defaults "awk" "demo.org" "contrib/*.el"))`

**Comment by l3kn** [comment]
"contrib/*.el" is even better, I've updated the installation instructions.

**Comment by ram535** [comment]
With the new instructions, I get this error:

```
Warning (initialization): An error occurred while loading ‘/home/last/.emacs.d/init.el’:

error: org-fc-keymap-hint.el:0:0: error: scan-error: (Unbalanced parentheses 1915 2368)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

```

**Comment by l3kn** [comment]
I've checked the file and there are no unbalanced parentseses anymore.
Maybe straight isn't using the most recent commit?

I'll check it with a minimal configuration later

**Comment by wedens** [comment]
@ram535 see https://github.com/l3kn/org-fc/issues/38. It was fixed recently.

**Comment by ram535** [comment]
I had to deleted manually the repo and the compile directory and the build-cache.el.
And now no errors are shown.

When doing `org-fc-demo`.
![image](https://user-images.githubusercontent.com/9011002/85954550-1c702580-b92d-11ea-9671-1937b89a7802.png)

After typing yes.

![image](https://user-images.githubusercontent.com/9011002/85954560-36116d00-b92d-11ea-881e-bacce09f1404.png)

When doing `org-fc-review` buffer.

![image](https://user-images.githubusercontent.com/9011002/85954587-5e00d080-b92d-11ea-969a-6c29b33ede94.png)

**Comment by yosevu** [comment]
Is there an equivalent way to fix this with just use-package without the :type and :files keywords? I'm not using straight.el.

`Error in private config: config.el, (file-missing Cannot open load file No such file or directory org-fc-hydra)`

**Comment by l3kn** [comment]
@ram535 I haven't set up straight.el to replicate this yet,
but I've pushed a change that includes the awk output in the lisp error message.

Can you try again with the latest commit and let me know which error you get?

@yosevu I'm not sure, for now I've moved all files from the `contrib/` folder to the root folder
so the `require`s should work again.

**Comment by ram535** [comment]
```
Followed link to /home/last/.emacs.d/straight/repos/org-fc/demo.org
org-fc-awk-index-paths: org-fc shell error: gawk: /home/last/.emacs.d/straight/build/org-fc/awk/utils.awk:43:     ts = mktime(time, 1);
gawk: /home/last/.emacs.d/straight/build/org-fc/awk/utils.awk:43:                        ^ 2 is invalid as number of arguments for mktime
```

**Comment by l3kn** [comment]
Which version of gawk are you using? (`gawk -V`)

`mktime` is documented as taking two arguments: https://www.gnu.org/software/gawk/manual/html_node/Time-Functions.html

**Comment by ram535** [comment]
GNU Awk 4.1.4, API: 1.1 (GNU MPFR 4.0.1, GNU MP 6.1.2)

**Comment by l3kn** [comment]
My gawk version is `GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)`

Is there a way to for you to update your version?
If not, we'll have to find a workaround.

Timestamps are parsed in awk because it's notably faster than parsing them in EmacsLisp,
but once org-fc has some caching built in that becomes less important.

**Comment by ram535** [comment]
It worked after installing gawk 5.1.0 from source.

Just a little detail. When reviewing  the demo the hydra doesn't appear like shows in the readme.
![image](https://user-images.githubusercontent.com/9011002/86519101-64d78980-bdec-11ea-9861-2213d82bd986.png)

**Comment by ram535** [comment]
Never mind. I saw the documentation and saw that I need to add `(require 'org-fc-keymap-hint)` to see the hydra.
Thanks.

**Comment by l3kn** [comment]
I'm glad it works now.

The image in the review is from a previous version,
I'll change it once the demo file is updated.
