### ISSUE TITLE
space in file names

### ISSUE THREAD

**Issue by gambhiro** [l3kn/org-fc#47]
Brilliant package!

I started a 'buffer' review in a file named `2020-10-25-123635 flashcards.org`, and the space broke the file access:

```
org-fc-awk-index-paths: Org-fc shell error: find: ‘/home/yume/wiki/2020-10-25-123635’: No such file or directory
find: ‘flashcards.org’: No such file or directory
```

**Comment by l3kn** [comment]
This should be fixed now

**Comment by gambhiro** [comment]
Confirming, it's good now!
