### ISSUE TITLE
expand org-fc-directories

### ISSUE THREAD

**Issue by gambhiro** [l3kn/org-fc#49]
Please expand `org-fc-directories`. I had it set as:

```
  (use-package org-fc
    :custom (org-fc-directories '("~/wiki"))
...
```

When I selected 'all' for review, it ran into a problem:

```
org-fc-awk-index-paths: Org-fc shell error: find: ‘~/wiki’: No such file or directory
```

**Comment by l3kn** [comment]
Weird, maybe different shells handle it differently?
I'm also using relative paths for my org-fc-directories and it's working as expected.

In addition to shell quoting the paths, they are also getting expanded now,
can you check if that fixes your problem?

**Comment by gambhiro** [comment]
Thanks, `~/wiki` is working now!
