### ISSUE TITLE
use-package defer option doesn't work

### ISSUE THREAD

**Issue by souew** [l3kn/org-fc#51]
When I use defer t for use-package I can't run any of org-fc commands because it isn't loaded.
How can I ensure lazy loading of org-fc?

```
; download org-fc manually
(when (not (file-directory-p "~/.config/emacs/custom-packages/org-fc/"))
    (shell-command "git clone https://git.sr.ht/~l3kn/org-fc ~/.config/emacs/custom-packages/org-fc/"))
(add-to-list 'load-path "~/.config/emacs/custom-packages/org-fc/")
....
(use-package hydra)
(use-package org-fc
    :ensure nil
    :defer t
    :load-path "~/.config/emacs/custom-packages/org-fc/"
    :custom (org-fc-directories '("~/documents/pim/flashcards/"))
    :config
(require 'org-fc-hydra)
(setq org-fc-source-path "~/.config/emacs/custom-packages/org-fc/"))
```

**Comment by l3kn** [comment]
In the [use-package documentation](https://github.com/jwiegley/use-package#notes-about-lazy-loading) it sounds like the issue might be that that loading of org-fc functions is never triggered.

Maybe using `:bind` or `:commands` with the main bindings/commands you use to interact with org-fc is a better option?

**Comment by souew** [comment]
Adding :bind for org-fc-dashboard exposes that command to be used when defer is t. I don't know what exactly gets loaded in that case, only that function or not, sorry I'm not a programmer, but I guess it will do.

**Comment by l3kn** [comment]
Does the dashboard show any useful information and can you start a review from there?

I can give it a try later this week and see if using `:bind` or `:command` with one of the main functions like `org-fc-review` or `org-fc-hydra/body` loads everything that's needed to use org-fc.

**Comment by souew** [comment]
Yes, after I get to dashboard all other functions also become available.

**Comment by l3kn** [comment]
That's good to know!

Can I close this issue?

**Comment by souew** [comment]
Of course.
