### ISSUE TITLE
Support for Org Roam Nodes

### ISSUE THREAD

**Issue by joshcho** [l3kn/org-fc#73]
Is there any support for org roam nodes where there is no headline in the file?

**Comment by l3kn** [comment]
I'm not familiar with org-roam nodes, do you mean support for flashcards that are just a single file without a headline?
org-fc uses headline tags to mark flashcards and headline properties to store the review data so there is no support for cards without a headline.

**Comment by joshcho** [comment]
Got it, that makes sense. I will try to figure something else out then. Thanks for the great package.
