### ISSUE TITLE
No bar with keys and and stats, heading does not expand when rating

### ISSUE THREAD

**Issue by dimitry12** [l3kn/org-fc#77]
I am on Emacs 28.1 with Doom [3.0.0-dev](https://github.com/doomemacs/doomemacs/commit/c44bc81a05f3758ceaa28921dd9c830b9c571e61), and [latest](https://github.com/l3kn/org-fc/commit/f64b5336485a42be91cfe77850c02a41575f5984) org-fc.

I've been on Emacs 27.0 and [Doom 2.0.9](https://github.com/doomemacs/doomemacs/commit/d300bb0f42c920c9afa460bc617adcb59f837e53) with org-fc [from 2020](https://github.com/l3kn/org-fc/commit/fccf4b93a20b09e52ab4279ccb179204c37add28) and everything works as expected, which makes me believe that I know how it should look like when everything works :D

I mostly don't understand Emacs but happy to follow the instructions and figure things out.

Here is what I can not resolve:
- instead of the bar at the bottom with session-stats and keys I am seeing a string at the top of the screen which indicates if I am in the flip- or rate- mode and some number;
- when I press the button corresponding to flip, the text at the top switches to "rate" but heading remains collapsed;
- if I exit session, I can't unfold the heading with org-mode saying it's empty.

![Screen Shot 2022-08-21 at 12 11 37 PM](https://user-images.githubusercontent.com/484357/185805577-772a3761-b66a-4e39-a8ac-d5e44067226d.png)

![Screen Shot 2022-08-21 at 12 11 44 PM](https://user-images.githubusercontent.com/484357/185805580-980dd52d-2506-4c3a-ba94-393a576b86bc.png)

![Screen Shot 2022-08-21 at 12 29 13 PM](https://user-images.githubusercontent.com/484357/185805584-f71a175f-bb93-4b91-a7ce-43d2772c4054.png)

I will greatly appreciate any help!

**Comment by dimitry12** [comment]
Downgrading to Emacs 27.1 does not fix this.

**Comment by dimitry12** [comment]
Downgrading to https://github.com/l3kn/org-fc/commit/fccf4b93a20b09e52ab4279ccb179204c37add28 does help. Will binary search from there :D

**Comment by l3kn** [comment]
I think between 2020 and now I changed the header / bottom lines to exclude the percentages for the current session
and made the “keymap-hints” optional through `(require 'org-fc-keymap-hint)`.

This doesn't explain why you can't unfold the headings which makes me think that something about how the review-data drawers and/or cloze holes are hidden is broken.

There might be a commit in that range that changes how this hiding is done,
parts of which could be incompatible with doom Emacs.

Let me know if you find the commit that breaks it,
then we can look into possible workarounds.

**Comment by l3kn** [comment]
There is no way to investigate this without further information,
feel free to reopen the issue.
