### ISSUE TITLE
What does "box" mean in REVIEW_DATA?

### ISSUE THREAD

**Issue by cashweaver** [l3kn/org-fc#79]
Is "box" a term meaning the number of times you've reviewed the card? I see the number incrementing as I review cards.

**Comment by cashweaver** [comment]
Looks like it's related to the [Leitner system](https://supermemo.guru/wiki/Leitner_system).

**Comment by l3kn** [comment]
You're right, the term “box” comes from the Leitner system and counts the number of consecutive correct reviews.

Cards in box 0 or 1 are treated differently by the spacing algorithm
and their ease doesn't change on failed reviews.

This prevents the “ease” value (you can think of it as the factor by which review intervals increase)
from dropping very low on new cards that take a while to review correctly for the first time.

**Comment by cashweaver** [comment]
Thanks!
