### ISSUE TITLE
Always ordered reveal sequence

### ISSUE THREAD

**Issue by jethrokuan** [l3kn/org-fc#8]
for a particular flashcard, is it possible for the order of reveal to be always ordered? i.e. if I have 5 deletions, I would like `@0` to come first, and `@4` to come last. What i'm noticing is that the order in which they appear is dependent on the review due date time.

Here's the flow I'm using, and the observed behaviour:

1. Create a flashcard, with deletion annotations
2. Use hydra to create `enumeration` flashcard

This creates entries in the table that have the exact same due date.

When I run a review, it looks goes through all enumerations, but in random order. To fix, I have to edit the timestamps.

**Comment by l3kn** [comment]
All due positions are shuffled before review.
Ideally, they should be ordered in a better way, here are some metrics that should be considered for that:

1. Positions of the same card should be spaced out as far as possible from each other
2. Positions of cloze cards should be revealed in order
3. The most "overdue" cards should be scheduled first (taking into account their interval, too)

I'm not sure what the best way to implement this would be.

**Comment by jethrokuan** [comment]
The order of importance for these metrics to me would be `2, 1, 3`. 3 can be accounted for by first sorting by due date, and then picking the last $N$ cards for review (Anki uses 20). Here 1 cloze card counts as 1 card, so all positions of the cloze card are picked for review.

Can't `1` be handled by queuing the card to the back if marked for `again`?

**Comment by l3kn** [comment]
By "positions of the same card" I mean e.g. the front / back of a double card
or multiple deletions of a cloze card.

> 3 can be accounted for by first sorting by due date, and then picking the last $N$ cards for review (Anki uses 20)

I'm not sure if it would make sense to limit review sessions to N cards,
I try to go through all cards in each time.

I'll look into how anki sorts cards for review.

**Comment by jethrokuan** [comment]
> I try to go through all cards in each time.

Me too, but I think one can always rerun the review function to take the next $N$ cards. The Anki decks grow up to 1000 flashcards, which is a bit much for 1 run.

**Comment by l3kn** [comment]
Quoting https://apps.ankiweb.net/docs/manual.html#siblings-and-burying

> When you answer a card that has siblings, Anki can prevent the card’s siblings from being shown in the same session by automatically burying them. 

https://gitlab.com/phillord/org-drill/-/blob/master/org-drill.el uses different classes of items
(failed, overdue, new, young-mature, old-mature) and proritizes review of some of these over the others: https://gitlab.com/phillord/org-drill/-/blob/master/org-drill.el

I'm not sure what the best way to implement this would be.

I'd like to keep the implementation as simple as possible, ideally just using a function that returns an integer for each card and that's used to order cards for review, with an option to limit each review session to the next $n$ cards.

An alternative would be introducing a concept of "review buckets", where positions of the same card are spread over different buckets and buckets of cards are reviewed one after another.

**Comment by jethrokuan** [comment]
I'm not sure either, but maybe I'm not using clozes correctly. I can always split up the cloze deletions into their own flashcards. So far it's been pretty okay. I must say the `org-fc` experience has been quite superior to Anki already :smile:

**Comment by l3kn** [comment]
A good first step might be enforcing ordering at least on the positions enumeration cards.

One problem with that is that the IDs of the positions / holes don't refect the logical order,
e.g. when later adding another element to the front of the list.

Because position of the same card spread out over time (due to the random fuzz applied to the intervals), this should become less of a problem after a few reviews.

**Comment by jethrokuan** [comment]
> A good first step might be enforcing ordering at least on the positions enumeration cards.

This sounds complex already, but it's all I wanted actually. Maybe my issue title was misleading

**Comment by l3kn** [comment]
I think I found an easy way to ensure the positions of a card always appear in the correct order during review.

Working with the new structured data format from #24,
the positions of each card can be combined with a __sorted__ list of random numbers,
then the positions can be flattened into a single list, sorted by these random numbers.

I'll fix this once #24 has been tested & merged
