### ISSUE TITLE
[Feature request] Support multiple "decks"

### ISSUE THREAD

**Issue by cashweaver** [l3kn/org-fc#87]
It would be nice to support the idea from Anki, etc, of Decks. A deck is a collection of cards. Users should be able to review decks independently of one another.

**Comment by cashweaver** [comment]
Looks like this is already possible using a context `:filter`.

**Comment by cashweaver** [comment]
1. Select a tag which will identify your new deck. I'll use `:deck_one` in this example.
2. Tag all of the cards to include in this deck with the tag
3. Define a new [context](https://www.leonrische.me/fc/review_contexts.html):
    ```el
    (add-to-list 'org-fc-custom-contexts
      '(deck-one . (:filter (tag "deck_one"))))
    ```
4. `org-fc-review` and select `deck-one`

**Comment by cashweaver** [comment]
Closing as the feature already exists. I think it's a good idea to reference the term "deck" as that's what incoming Anki users will expect.

**Comment by l3kn** [comment]
Review contexts are a more advanced variant of this,
to accommodate a “zettelkasten” style with many files containing only a few cards each.

Alternatively you could create a file for each deck and either create a context specific for that file,
or start a review session from within that file.

Let me look into integrating the documentation files into this repo,
then we can work on some kind of “migrating from Anki” guide.
