### ISSUE TITLE
[Documentation] Replicate documentation into repo

### ISSUE THREAD

**Issue by cashweaver** [l3kn/org-fc#89]
Replicate the [documentation](https://www.leonrische.me/fc/index.html) into the repo.

**Comment by l3kn** [comment]
That's a good idea. The documentation is already written in org-mode files, I just need to figure out how to do this in a way that doesn't break the setup I'm using to generate the html version.

**Comment by l3kn** [comment]
Org files are now available in the `docs/` folder.
I'm not sure how to handle images yet, ideally they shouldn't be tracked by git.
