### ISSUE TITLE
Deletion of image files don't show image

### ISSUE THREAD

**Issue by jethrokuan** [l3kn/org-fc#9]
I've found that image deletions don't work, which seems to be a common kind of deletion.

**Comment by l3kn** [comment]
I managed to replicate this bug,
weirdly, adding newlines or spaces around the image link fixes it for me:

``` org
{{
[[file:image.png]]
}@0}

{{ [[file:image.png]] }@1}
```

**Comment by jethrokuan** [comment]
I can confirm whitespace resolves it... guess it's a non-issue then!

**Comment by l3kn** [comment]
I'd say this is still an issue, I'm just not sure if there is anything that could be done on the level of this package to resolve it.

I'll add a note to the readme about this.

**Comment by amano-kenji** [comment]
Is this still an issue? I'm considering gradually moving anki cards to org-fc because it's almost impossible to reproducibly build anki. That's why linux distributions provide binary builds of anki instead of building anki from source.

I don't want to be stuck with binary builds.

**Comment by l3kn** [comment]
Images in non-cloze cards should work out of the box. I've tested it with cloze deletions
and it seems that the whitespace fix outlined here is no longer necessary
but `(org-display-inline-images)` needs to be run either with one of the hooks provided for org-fc
or added with a small change to the implementation of the cloze card type.

Before moving away from Anki, please be aware that org-fc doesn't yet have a stable implementation
of the new FSRS spacing algorithm available in Anki.

**Comment by amano-kenji** [comment]
I don't require a stable spacing algorithm. It just needs to be good enough.

But, I require a stable user interface and easy configuration. Is org-fc production-ready?

**Comment by l3kn** [comment]
@amano-kenji What do you mean by production-ready? I've been developing and using it for some years now and in that time I've done over 400k reviews so I'd say it's stable enough.

**Comment by amano-kenji** [comment]
I think that's ready enough.

**Comment by l3kn** [comment]
In the current state of functionality, I think it will last as long as there are some people who find it useful enough to put a little bit of work when there are changes to org-mode or Emacs that require an adjustment of the org-fc code.
